language: python
python:
  - "2.7"
install:
  - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ precise main universe"
  - sudo apt-get install -y python-twisted
  - sudo apt-get install -y python-xattr
  - pip install -v python-gnupg
script: python qa/run.py
